import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-custom-gray-primary text-custom-white w-full">
          <div className="w-full min-h-screen max-w-6xl mx-auto">
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
